---
- name: Windows Hardening Playbook
  hosts: apex_one_windows
  vars:
    windows_firewall_profiles:
      - domain
      - private
      - public
    windows_firewall_block_rule:
      name: Block_outbound_traffic
      description: Block outbound HTTP traffic
      port: 80
    windows_firewall_allow_rule:
      name: Allow_outbound_https_traffic
      description: Allow outbound HTTPS traffic
      port: 443

  tasks:
    - name: Ensure Windows firewall service is on enabled
      ansible.windows.win_firewall:
        state: enabled
        profiles: "{{ windows_firewall_profiles }}"
      tags: [firewall, hardening]

    - name: Block outbound traffic for all profiles
      community.windows.win_firewall_rule:
        name: "{{ windows_firewall_block_rule.name }}"
        description: "{{ windows_firewall_block_rule.description }}"
        state: present
        enabled: true
        direction: out
        action: block
        protocol: tcp
        remoteport: "{{ windows_firewall_block_rule.port }}"
        profiles: "{{ windows_firewall_profiles }}"
      tags: [firewall, hardening, network]

    - name: Allow outbound https traffic
      community.windows.win_firewall_rule:
        name: "{{ windows_firewall_allow_rule.name }}"
        description: "{{ windows_firewall_allow_rule.description }}"
        state: present
        enabled: true
        direction: out
        action: allow
        protocol: tcp
        remoteport: "{{ windows_firewall_allow_rule.port }}"
        profiles: "{{ windows_firewall_profiles }}"
      tags: [firewall, hardening, network]
